# Generated by Django 2.2.5 on 2019-12-10 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('Phone1', models.CharField(max_length=150, verbose_name='Телефон 1')),
                ('Phone2', models.CharField(blank=True, max_length=150, verbose_name='Телефон 2')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Наименование')),
                ('full_name', models.CharField(blank=True, max_length=1024, verbose_name='Наименование полное')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('address1', models.CharField(blank=True, max_length=1024, verbose_name='Адрес 1')),
                ('address2', models.CharField(blank=True, max_length=1024, verbose_name='Адрес 2')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
    ]
