# Generated by Django 2.2.5 on 2019-12-16 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20191216_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='name',
            new_name='с',
        ),
    ]
