# Generated by Django 2.2.5 on 2019-12-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20191216_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyer',
            options={'verbose_name': 'Заказчик', 'verbose_name_plural': 'Заказчики'},
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='Phone1',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='address1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='Phone2',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='full_name',
        ),
        migrations.AddField(
            model_name='buyer',
            name='email',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='email'),
        ),
    ]
