# Generated by Django 2.2.5 on 2019-12-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_auto_20191217_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='email',
            field=models.CharField(default='', max_length=150, verbose_name='email'),
        ),
    ]
