# Generated by Django 2.2.5 on 2019-12-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_auto_20191217_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='Phone',
            field=models.CharField(max_length=150, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='address',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Адрес'),
        ),
    ]
