# Generated by Django 2.2.5 on 2019-12-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_auto_20191217_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='Phone',
            field=models.CharField(blank=True, max_length=150, verbose_name='Телефон'),
        ),
    ]
