# Generated by Django 2.2.5 on 2019-12-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_auto_20191218_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='Phone',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Фамилия'),
        ),
    ]
