# Generated by Django 2.2.5 on 2019-12-03 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('name_full', models.CharField(blank=True, max_length=1024, verbose_name='Наименование полное')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(blank=True, decimal_places=0, default='0', max_digits=15, verbose_name='Цена')),
                ('vendor_code', models.CharField(blank=True, max_length=150, verbose_name='Артикул')),
                ('slug', models.SlugField(blank=True, max_length=10, verbose_name='Url')),
                ('is_catalog', models.BooleanField(default=False, verbose_name='Это каталог')),
                ('parent_catalog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goodapp.Good', verbose_name='Родительский каталог')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
