# Generated by Django 2.2.5 on 2019-12-03 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0002_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='parent_catalog',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='goodapp.Good', verbose_name='Родительский каталог'),
        ),
    ]
