# Generated by Django 2.2.5 on 2019-12-03 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0005_auto_20191203_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='image1000',
            new_name='image1200',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='image420',
            new_name='image570',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='image174',
            new_name='image90',
        ),
    ]
