# Generated by Django 2.2.5 on 2019-12-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0006_auto_20191203_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='meta_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='meta description'),
        ),
        migrations.AddField(
            model_name='good',
            name='meta_name',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='meta name'),
        ),
    ]
