# Generated by Django 2.2.5 on 2019-12-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0008_good_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=0, default='0', max_digits=15, verbose_name='Остаток'),
        ),
        migrations.AlterField(
            model_name='good',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=0, default='0', max_digits=15, verbose_name='Старая цена'),
        ),
    ]
